### PR TITLE
Add optional image and caption attributes to Connector and Cable/Bundle nodes

### PR DESCRIPTION
**Pull request by kvid**
- This fixes issue #27.
- Edit: All scaling attributes described in https://github.com/formatc1702/WireViz/issues/27#issuecomment-670141605 are now implemented.

### CODE REVIEW

**Comment by formatc1702** [comment]
Nice. You could build upon #136 and set `feature/gv-html-refactor` as the base branch to take advantage of the refactored code for cables :)

**Comment by kvid** [comment]
> Nice. You could build upon #136 and set `feature/gv-html-refactor` as the base branch to take advantage of the refactored code for cables :)

This rebase is not yet done, as it depends on your answer(s) to my https://github.com/formatc1702/WireViz/pull/136#issuecomment-668737738 about styling, but this PR is ready for testing the functionality.

Finalizing this PR also depends on your answer to my https://github.com/formatc1702/WireViz/issues/27#issuecomment-668704773 that also might require a few changes.

**Comment by formatc1702** [comment]
I did not actively close this PR; but this is what I feared when I wrote my [comment](https://github.com/formatc1702/WireViz/pull/136#issuecomment-673289459) in #136.

- Edit this PR to point to the `dev` branch instead of `gv-html-refactor`
- Open a new PR based on `dev` and submit the changes there.

**Comment by kvid** [comment]
@formatc1702 wrote:
> @kvid if you are wondering why this is marked as closed:
> I did not actively close this PR; but this is what I feared would happen when I wrote my [comment](https://github.com/formatc1702/WireViz/pull/136#issuecomment-673289459) in #136.
> The base branch no longer exists after the rebasing of #136, and GitHub has automatically closed the PR because of that.

I'm sorry, I misunderstood your rebase plan. I thought you were planning an interactive rebase to fix the commit history and keep the feature branch - not merge it into `dev` and kill the feature branch.

> You probably have two options now:
> 
> * Edit this PR to point to the `dev` branch instead of `feature/gv-html-refactor`. Perhaps you can then reopen the PR.

I could edit the PR, but only the name, not the base branch.

If I had understood you would delete your feature branch, then I would have changed the base branch of my PR **before** your deleted your feature branch.

> * Open a new PR based on `dev` and submit the changes there.

I have already created PR #153 that is now ready for review.

**Comment by formatc1702** [comment]
Ahh, I see.
Usually, after a feature is merged into dev (doesn't matter whether merge/rebase/squash), the feature branch is no longer needed, and since you approved the changes, that's what happens. Sorry if it was unexpected!
Anyway, thanks for the new PR. Will take a look in the next few days.

**Pull request closed without merging**
