### PR TITLE
Refactor depency handling, installation, and add a few features

### PR DESCRIPTION
**Pull request by n42**
Hey,

Great idea and immediately useful, for me. I've done some quick and dirty - but fairly major - refactoring here as follows for my own sake - use it if you wish.

- Got rid of the graphviz and pyyaml dependencies that were included in the repo
- Add a setup.py script with some preliminary metadata and the required dependencies, in order to 'pip install' instead. It should be fairly easy to get it onto PyPi. 
- Updated documentation to reflect the above, rebuilt the demos
- Broke out the argument parsing to a separate function and removed the defunct 'test' default input (the file you pointed to wasn't included in the repo, so running without an argument crashed rather than printed the help)
- Feature: add a field for specifying exact cable SKUs and the like (_specified_cable_ key)
- Feature: add automatic AWG->mm2 conversion as well, when using _show_equiv_. Some minor refactoring there as well, modified ex06 to show it.

### CODE REVIEW

**Comment by SuperRoach** [comment]
I like this implementation to make it easier to use! One thing that could make it even easier is the first user setup.

- User git clones repo

- Either on bare metal installing python or spins up a dev container that has python3 preinstalled

- does pip3 install -e . 

- python3 src/wireviz/wireviz.py examples/ex03.yml (run a sample file)

Will give a 
`Traceback (most recent call last):
  File "src/wireviz/wireviz.py", line 639, in <module>
    main()
  File "src/wireviz/wireviz.py", line 636, in main
    parse(args.input_file, file_out=args.output_file, gen_bom=args.generate_bom)
  File "src/wireviz/wireviz.py", line 615, in parse
    h.output(filename=file_out, format=('png','svg'), gen_bom=gen_bom, view=False)
  File "src/wireviz/wireviz.py", line 218, in output
    d.render(filename=filename, directory=directory, view=view, cleanup=cleanup)
  File "/usr/local/lib/python3.8/site-packages/graphviz/files.py", line 207, in render
    rendered = backend.render(self._engine, format, filepath,
  File "/usr/local/lib/python3.8/site-packages/graphviz/backend.py", line 221, in render
    run(cmd, capture_output=True, cwd=cwd, check=True, quiet=quiet)
  File "/usr/local/lib/python3.8/site-packages/graphviz/backend.py", line 167, in run
    raise ExecutableNotFound(cmd)
graphviz.backend.ExecutableNotFound: failed to execute ['dot', '-Tpng', '-O', 'ex03'], make sure the Graphviz executables are on your systems' PATH`

I'm guessing it's because the png and svg libraries it's calling arn't there yet.

**Comment by n42** [comment]
> I like this implementation to make it easier to use! One thing that could make it even easier is the first user setup.
> 
> * User git clones repo
> * Either on bare metal installing python or spins up a dev container that has python3 preinstalled
> * does pip3 install -e .
> * python3 src/wireviz/wireviz.py examples/ex03.yml (run a sample file)
> 
> Will give a
> `Traceback (most recent call last): File "src/wireviz/wireviz.py", line 639, in <module> main() File "src/wireviz/wireviz.py", line 636, in main parse(args.input_file, file_out=args.output_file, gen_bom=args.generate_bom) File "src/wireviz/wireviz.py", line 615, in parse h.output(filename=file_out, format=('png','svg'), gen_bom=gen_bom, view=False) File "src/wireviz/wireviz.py", line 218, in output d.render(filename=filename, directory=directory, view=view, cleanup=cleanup) File "/usr/local/lib/python3.8/site-packages/graphviz/files.py", line 207, in render rendered = backend.render(self._engine, format, filepath, File "/usr/local/lib/python3.8/site-packages/graphviz/backend.py", line 221, in render run(cmd, capture_output=True, cwd=cwd, check=True, quiet=quiet) File "/usr/local/lib/python3.8/site-packages/graphviz/backend.py", line 167, in run raise ExecutableNotFound(cmd) graphviz.backend.ExecutableNotFound: failed to execute ['dot', '-Tpng', '-O', 'ex03'], make sure the Graphviz executables are on your systems' PATH`
> 
> I'm guessing it's because the png and svg libraries it's calling arn't there yet.

Ah, apart from the graphviz python package (bindings) it also requires the actual graphviz system package; pip doesn't pull that for you. Already had it installed, so didn't catch that -- it's a documentation issue, i'll drop in a fix in the install notes and add to the PR, but an ```apt-get install graphviz``` (or your equivalent package manager command if running anything other than debian derivatives) should sort you out, @SuperRoach

**Comment by n42** [comment]
cb1d6cd fixes the install instructions as above; verified that no other dependencies are required using a clean dockerized ubuntu.

**Comment by formatc1702** [comment]
This looks great! I'll try to merge this in the next few days :)

**Comment by formatc1702** [comment]
What would be the best way to split this into multiple merges, to separate the dependency handling + installation from the added features?
This is my first time managing a collaborative project like this, so any pointers are appreciated!

**Comment by formatc1702** [comment]
I've cherry picked the commits relevant to dependency handling and refactoring, skipping the added features for now. Will push once I confirm everything works.

**Comment by formatc1702** [comment]
Integrated into dev branch with 7060c38f07c9eba575c4acc436eff191a6b9e192 , please confirm that everything went smoothly! I made some minor changes to make the build_examples.py script work again.

**Comment by formatc1702** [comment]
I've [added the project to PyPI](https://pypi.org/project/wireviz/) 🎉  There's plenty of things to learn, but at least it's out there.

Any further assistance on this topic will be highly appreciated, as I have zero previous experience with PyPI and the intricacies of packaging a project...

**Pull request merged**
