### PR TITLE
Allow cleaning of examples

### PR DESCRIPTION
**Pull request by aakatz3**
build_examples supports cleaning examples and intelligently will detect new examples.

SUGGESTION: When merging into dev, require
```
build_examples.py clean
```

and then only build when merging into master branch

This should allow easier merges, especially from windows, and I am using it as part of a resolution to one of the requests in #17

### CODE REVIEW

**Comment by formatc1702** [comment]
This looks like a really useful improvement! Thanks!

**Comment by formatc1702** [comment]
Any idea how it chooses the order of the files? Any quick way to fix this?
See my console output when I run the script:

```
(venv) wireviz $ python build_examples.py 
../../examples/ex09.yml
../../examples/ex08.yml
../../examples/ex01.yml
../../examples/ex03.yml
../../examples/ex02.yml
../../examples/ex06.yml
../../examples/ex07.yml
../../examples/ex05.yml
../../examples/ex04.yml
../../examples/demo01.yml
../../examples/demo02.yml
../../tutorial/tutorial08.yml
../../tutorial/tutorial02.yml
../../tutorial/tutorial03.yml
../../tutorial/tutorial01.yml
../../tutorial/tutorial04.yml
../../tutorial/tutorial05.yml
../../tutorial/tutorial07.yml
../../tutorial/tutorial06.yml
```

**Comment by formatc1702** [comment]
Also, I'm not sure cleaning up the examples is the best course of action, because then the [readme of the `dev` branch](https://github.com/formatc1702/WireViz/tree/dev) would include references to nonexistent files; same for the tutorial and example galleries.

What I've been doing is simply discarding any changes I've made to the output files before commiting anything to `dev`.

As the project matures, there probably will be less and less changes that affect the output files, but who knows.

**Comment by formatc1702** [comment]
Perhaps one option would be to keep examples out of the repo completely (by `.gitignore`ing the entire directory), and curating a separate `wireviz-gallery` repo that can be rebuilt and updated at will. The WireViz readme could directly link to those files on the other repo. This would avoid links to missing files.

**Comment by kvid** [comment]
Personally, I have actively used the input files together with the output files that don't depend on the Graphviz version as regression tests to verify that my commits either don't change any output or produce the expected output diff. That's also why I suggested issue https://github.com/formatc1702/WireViz/issues/63

I would therefore prefer to keep these files unless the regression testing can be secured some other way. Why not change the `clean` action to do `git checkout -- {generated files}` or something similar?

**Comment by kvid** [comment]
If `build_examples.py` is changed to write generated files to a `_built` subfolder unless some action argument specify to overwrite the committed files, then it will be easy both to compare differences side by side and to ignore the subfolder when committing. What do you think?

**Pull request merged**
