### PR TITLE
Move BOM management and HTML functions to separate modules

### LINKED ISSUE #151: [internal] Create a new module for helper functions to each output format?
As the number of helper functions for generating HTML is increasing, maybe we should move them into a new `wv_html.py` file? See also the excerpt from a recent discussion below.

> > > Do you have a set of rules or recommendations about where to insert newlines, i.e. what HTML tags can be on the same row, and when should they be separated?
> > 
> > 
> > No hard rules right now, and it's not terribly important. Cells are usually in one row (`<td>...</td>`). Multiple short opening tags in sequence tend to go together (`<tr><td>` and the respective closing tags for the outermost table, for example). Row breaks (`</tr><tr>`) could go in one line but are usually split because they come from iterations of a loop.
> 
> Nice. Should we but these words into a comment in the code as soft recommendations?
> 
> Maybe into `wv_helper.py`, or into a new `wv_html.py` and move the increasing number (at least in my PR #137) of html related helper functions there too?

A new module for the HTML stuff sounds good, as a separate issue/PR!

> > > Have you considered a single space indentation for each sub-level of HTML tag structure?
> > 
> > 
> > ~I thought about it but decided against it; the gains are marginal, the readability of the Python code would suffer; plus it's easy to pass the HTML through some auto-formatter afterwards if one really needs to analyze the structure at some point.~
> > Edit: thinking about it some more, it might not be such a bad idea, I'll try it out and push a commit.
> 
> It is not a major issue to me, especially if the Python code gets more complicated and less readable. I will wait and see what you suggest.

It was less painful than anticipated, and I do like the output! Have a look at the latest commit. This will hopefully be the last change before the merge.

_Originally posted by @formatc1702 in https://github.com/formatc1702/WireViz/pull/136#issuecomment-673109385_

### PR DESCRIPTION
**Pull request by formatc1702**
Closes #151.

### CODE REVIEW

**Comment by formatc1702** [comment]
Moving the BOM modules to a separate file might be trickier than expected...

**Comment by kvid** [comment]
I know this is WIP, but in case these hints might help you:
- `get_additional_component_table` and `manufacturer_info_field` is not used for BOM and might rather belong to `wv_gv_html.py`.
- `clean_whitespace` is not used for diagram output. It is rather generic, but currently used for BOM.
- `remove_links` is rather generic and mainly used for diagram output, but also for `.bom.tsv` output.

**Comment by formatc1702** [comment]
Thanks, yes, I'm moving things around as I progress.

Currently, `build_examples.py` runs without errors, but BOMs are empty.

It seems things are getting lost inside `generate_bom()` when passing into from the `bom_entries` variable to `bom`.

I think the BOM generation code has grown quite complex, so I need some time to understand it, and make sure we are not passing around more objects than needed, that functions end up in the correct modules, etc.

**Comment by formatc1702** [comment]
> * `get_additional_component_table` and `manufacturer_info_field` is not used for BOM and might rather belong to `wv_gv_html.py`.

- `get_additional_component_table` is tightly linked to `get_bom_index()` and that one to the actual `bom()` function, therefore I will choose to leave it in `wv_bom.py`, at least until we refactor the BOM code, which should be a separate PR.
- `manufacturer_info_field` is also used in `component_table_entry` for generating the mini-BOM within a component node, and it's related to the typical BOM fields `pn` etc., so I think it also belongs in `wv_bom.py`. Also, it does not generate any actual HTML.

> * `clean_whitespace` is not used for diagram output. It is rather generic, but currently used for BOM.
> * `remove_links` is rather generic and mainly used for diagram output, but also for `.bom.tsv` output.

I agree they're generic enough to move to `wv_helper.py` since they are not really tied to BOM or HTML stuff.

**Comment by formatc1702** [comment]
`build_examples.py` now runs without errors, and the output is exactly the same as when using the `dev` branch.

Therefore, unless no glaring errors show up, I would like to merge this soon. Refactoring and optimization of the affected functions can happen in a later PR. Thanks!

**Review by kvid — APPROVED** [review]
I can verify that the output is unchanged when generating examples. I do have some simplifications of `wv_bom.py` in my local repo that I plan to push to a new PR when this is merged, as you requested.

**Pull request merged**
