### PR TITLE
Adding ability to export PNG data directly to other programs.

### PR DESCRIPTION
**Pull request by slightlynybbled**
I would like to build on your tool with a GUI.  This pull request puts the beginnings of the API into the project.

# Example Usage

    from wireviz.wireviz import parse
    
    # taking the string from a text entry frame (tkinter style)
    f_in = StringIO(self._text_entry_frame.get())
    
    # put the png data directly into the `data` variable for use later
    data = parse(f_in, return_types='png')
    
    # can use the image data for whatever I want now... in this case, I'll just save it
    # but I could put it on a canvas and preview if I like
    with open('data.png', 'wb') as f:
        f.write(data)

# Future Work

At this time, I only added support for `png`, but I left room in there to potentially add more types and even multiple types.  Also put the beginnings of a docstring in there to explain my changes, but didn't fill it out fully just in case you wanted to put your own words in there.

### CODE REVIEW

**Comment by formatc1702** [comment]
Thanks, I like the idea a lot. I merged it and took the liberty to rewrite the addition to the parse() function (144c99e0216b7cd83988ccf2f636d8bbabd96692), let me know what you think.

**Comment by slightlynybbled** [comment]
Thanks for accepting the merge.

The GUI code that uses your repo: [wireviz-gui](https://github.com/slightlynybbled/wireviz-gui)

Installation is a bit complicated at the moment, but that will be simplified as the code bases become more stable.  Look forward to seeing what the future brings!

**Comment by formatc1702** [comment]
@slightlynybbled, [here](https://chris.beams.io/posts/git-commit/#imperative)'s a little recommendation for future commit messages, both here and in your own repos, regarding the use of imperative mood. I noticed the messages in your wireviz-gui repo might benefit from this :)

**Comment by slightlynybbled** [comment]
Thank you for making me aware. I had no idea this was a thing!

**Comment by slightlynybbled** [comment]
Just wanted to let you know that I created a bundled executable based on your current dev branch.

https://github.com/slightlynybbled/wireviz-gui

https://github.com/slightlynybbled/wireviz-gui/releases

Your repository is credited and linked in the `About` menu.

Not feature-rich yet, but a better workflow for those unhappy with the command line...

Thank you for this package!  As it becomes more mature, I will continue to add features!

**Pull request merged**
