### PR TITLE
Add infrastructure to make it possible to deploy this as a docker service into swarm or kubernetes

### PR DESCRIPTION
**Pull request by elbosso**
I basically used the code in the project and wrapped some more around it that does all that is needed to be able to offer some of the functionality as kind of a micro service: The html file included src/app/static/index.html describes what can be done - at the moment, the service expects a yaml file and returns always the rendered PNG unless the client specifies the header accepts with value image/svg+xml with the POST request - in that case, the rendered SVG is returned. One could of course add features as for example returning the BOM or returning an archive containing BOM, PNG and SVG. 

The included docker-compose file already contains all that is needed to deploy the container as-is but it also contains everything that is needed to run it with a traefik 2 proxy

### CODE REVIEW

**Comment by Tyler-Ward** [comment]
[plantuml](https://plantuml.com/) has a similar setup to allow for online generation but also allows for get requests. To allow opperation without needing to use a post request (such as an embedded image) plant uml gz deflates the data then base 64 encodes it to create a get url. 

The features added in #55 might be worth using here rather than the use of temporary files.

**Comment by elbosso** [comment]
> [plantuml](https://plantuml.com/) has a similar setup to allow for online generation but also allows for get requests. To allow opperation without needing to use a post request (such as an embedded image) plant uml gz deflates the data then base 64 encodes it to create a get url.
> 
> Also the features added in #55 might be worth using here rather than the use of temporary files.

plantuml is actually where i got the idea from. My last commit adds a few cosmetic changes to the web application - i will start looking into the "get" variant tomorrow

**Comment by formatc1702** [comment]
Thanks for this contribution. Since I'm not familiar with Docker/Swarm/Kubernetes, and I have other open things to work on, this might not get merged in the near future. It _is_ an area that I want to focus on learning soon, though.

If someone is able to test this contribution, please let me know.

In the meantime, @elbosso please have a look at the guide for writing [good commit messages](https://chris.beams.io/posts/git-commit/#imperative), especially point 5 :-)

Cheers!

**Comment by slightlynybbled** [comment]
Honestly, this is a very cool idea, but strikes me as a repository of its own.  The author of the package, by accepting this sort of pull request, is agreeing to maintain the code for ... eternity.  By keeping wireviz a command-line-like utility, we can keep the author focused.  My recommendataion would be for @elbosso to create his/her own repository that implements these features and uses `wireviz` as a dependency.

**Comment by elbosso** [comment]
> Honestly, this is a very cool idea, but strikes me as a repository of its own. The author of the package, by accepting this sort of pull request, is agreeing to maintain the code for ... eternity. By keeping wireviz a command-line-like utility, we can keep the author focused. My recommendataion would be for @elbosso to create his/her own repository that implements these features and uses `wireviz` as a dependency.

Well, I pondered this for some time and I decided to try it this way. However - your point is valid so I would do exactly that if the maintainer(s) decide against integration of the pull request...

**Comment by formatc1702** [comment]
>  The author of the package, by accepting this sort of pull request, is agreeing to maintain the code for ... eternity.

Thanks @slightlynybbled for expressing my gut feeling in a concise way. Especially since I am not familiar with the technologies used in this proposal, it might cause frustration for everyone involved if I just merge this and have no idea how it works or how to maintain it.

@elbosso let's do that then, please create a separate repo as suggested. @slightlynybbled is already doing a fantastic job preparing a GUI for WireViz, so this could be another 'spinoff', if you will.

I will close this issue but I'm happy to continue the discussion! Thanks everybody.

**Comment by elbosso** [comment]
For the time being, my repo https://github.com/elbosso/WireViz is a fork of this one here. It is online and usable, though large parts of howto-docker are still missing in the readme. Feel free to look it up...

**Comment by formatc1702** [comment]
I'm not sure if a fork is the right way to go... wouldn't it make more sense to make a new repo and add WireViz as a dependency/requirement? Kind of like [WireViz](https://github.com/slightlynybbled/wireviz-gui) is doing?

Others may chime in if I'm wrong, of course.

**Comment by elbosso** [comment]
@Tyler-Ward, @formatc1702 , @slightlynybbled : Thanks to your ideas and feedback, a new project was born: https://github.com/elbosso/plantumlinterfaceproxy/blob/master/README.md. A little youtube video as explanation is to be found here:  https://www.youtube.com/watch?v=gB1UfRYJoYc 
Many, many thanks!

**Pull request closed without merging**
