### PR TITLE
Modify CLI interface

### PR DESCRIPTION
**Pull request by slightlynybbled**
See issue #60 

From an interface standpoint, I mostly followed the recommendations of @formatc1702.  

There are minor differences put in place for convenience and compatibility with `click`.

Windows example:

    > python src\wireviz\wireviz.py examples\demo01.yml -o png -o svg

Linux example:

    > python src/wireviz/wireviz.py examples/demo01.yml -o png -o svg

The proposed pull request also assumes some architectural changes within the package that the author may not be comfortable with.  It is my opinion that the `Harness` object should be highly concerned with generating the correct outputs and less concerned with file output manipulations, which explains the structure that I chose.  I simply chose to write the outputs from `parse()` at the highest level.  I'm assuming that expanding the `Harness()` object to support formats as properties is the most straightforward way of expanding the package and that the idea of the `Harness()` object actually writing to files itself will become awkward as time goes on.  The idea currently implemented as properties `svg` and `png` could easily be expanded to create other properties `csv`, `html`, etc and allow higher-level code to do the coordination and file io with returned data.

There are still some rocks in here, and I don't expect the PR to be accepted in its current form, but I do believe that it is easier to maintain and expand with this as the starting at this point.

### CODE REVIEW

**Comment by slightlynybbled** [comment]
Output of help file:

```
(venv) C:\_code\WireViz>python src\wireviz\wireviz.py --help
Usage: wireviz.py [OPTIONS] INPUT_FILE

  Take a YAML file containing a harness specification and, utilizing
  GraphViz, translate that specification into various output formats.
  Example:

      $>wireviz my_input_file.yml -o png -o svg

Options:
  -p, --prepend TEXT  a YAML file containing a library of templates and parts
                      that may be referenced in the `input_file`

  -o, --out TEXT      specify one or more output types to be generated;
                      currently supports "png" "svg"

  --help              Show this message and exit.

```

**Comment by formatc1702** [comment]
Cool!
Is it possible to list multiple output types without requiring `-o` for each one?
`wireviz inputfile.yml -o png svg csv`
If it's a limitation of `click`, I guess we're out of luck.

**Comment by slightlynybbled** [comment]
It is a limitation of `click`.  I am fine with this limitation b/c it is very much in sync with other common CLIs (gcc, for instance).  If you want to get around it, you might make an interpreted string instead:

    $>wireviz inputfile.yml -o "png svg csv"

I don't love this, but it is your call.

**Comment by formatc1702** [comment]
> The proposed pull request also assumes some architectural changes within the package that the author may not be comfortable with.

What I'm not comfortable with, is the current state of things. You raise a point I've had in the back of my mind for a while, so I'm very thankful for this proposal.
Ideally, we could offload all the output file handling into a separate module, `wv_output.py` or similar to separate the harness logic from all the CSV, TSV and HTML output. 
@aakatz's functions from the `bom_helper.py` file submitted in #116 would also be well suited for inclusion in this module.

I have a proposal: @aakatz can submit a pull request for the improved CSV/TSV output to @slightlynybbled, who is welcome to refactor `wireviz.py` and `Harness.py` to address this very issue, including the new CSV/TSV.

If both contributors agree with this, I will close #116 without merging, in favor of including its commits as part of #123 (this)
In order not to further complicate things, I'd like to move the HTML output as-is to this new module... the HTML itself is a story for another day (#74).
Would this foreseeably cause trouble with any of the other open PRs?

**Comment by formatc1702** [comment]
> If you want to get around it, you might make an interpreted string instead:
> 
> ```
> $>wireviz inputfile.yml -o "png svg csv"
> ```
> 
> I don't love this, but it is your call.

Nope, let's stick to your proposal then.

**Comment by slightlynybbled** [comment]
I'm ok with this.  It jives nicely with [separation of concerns](https://en.wikipedia.org/wiki/Separation_of_concerns), which I hold dear.

**Comment by formatc1702** [comment]
The way I see it, we would need a couple of functions:
- `output_bom()` based on `generate_bom_outputs()` from #116 
- `output_html()`
and some simpler functions:
- `output_png()`
- `output_svg` <-- probably based on the existing `png()` and `svg()` properties
- `output_gv` should be trivial

**Comment by slightlynybbled** [comment]
Perhaps I misunderstood something.

Where are the `output_<format>()` functions to go?  What are expected parameters?  Expected returns?

**Comment by formatc1702** [comment]
I thought you wanted to move code out of 'Harness.py`, specifically anything concerning file handling.

That's why I proposed the `wv_output.py` module to house these functions. BOM and HTML output (and PDF in the future) are not trivial, and I don't like them [sitting in 'Harness.py`](https://github.com/formatc1702/WireViz/blob/dev/src/wireviz/Harness.py#L300L332), since it violates the separation of concerns (correct?).

And if we move that way, I was wondering whether the simpler PNG, SVG and GV outputs should then also go into the new module. But perhaps that would be overdoing it, since they are [much more compact](https://github.com/formatc1702/WireViz/blob/dev/src/wireviz/Harness.py#L296L297).

As long as the CLI parser handles all outputs gracefully, it probably doesn't matter where the actual file output for each file type happens, right?

**Comment by slightlynybbled** [comment]
Ok, no problem... i thought you meant to stuff `output_X()` functions onto `Harness`.  Can do.

**Comment by formatc1702** [comment]
> i thought you meant to stuff `output_X()` functions onto `Harness`

oh dear, that would be the opposite of what we want to achieve, wouldn't it? 😅 Looking forward to a cleaner codebase! 😎

**Comment by aakatz3** [comment]
Agreed on the separate functions, it may be a good idea to do it similar to how the SVG and PNG functions currently allow piping, and then write them to disk.

Whether YAML, arguments, and/or a central/default config file control the output, I'm not sure, but all seem decent (and ideally all three would be most flexible, even if the config has to be an additional argument)

**Comment by aakatz3** [comment]
Agreed on the separate functions, it may be a good idea to do it similar to how the SVG and PNG functions currently allow piping, and then write them to disk.

Whether YAML, arguments, and/or a central/default config file control the output, I'm not sure, but all seem decent (and ideally all three would be most flexible, even if the config has to be an additional argument)

**Comment by slightlynybbled** [comment]
I refactored somewhat, but I'm not done yet...

**Comment by slightlynybbled** [comment]
I made some pretty major changes:

 - `Harness` class is no longer capable of generating files
 - All file input/output are handled in `main()`
 - Integrated bones of CSV file generation provided by @aakatz3 (significant refactor to provide data rather than write files)
 - File generation path is much more consistent than previous versions
 - Some refactor of `build_examples.py` to utilize `main()` (same function that the CLI will use)
 - Removal of `parse_file()` function from `wireviz.py` (it was only being used by `build_examples.py`)
 - Refactor of `Harness.bom()` and `Harness.bom_list()` methods to be private using the underscore convention.

I'm sure that there is still somef cleanup to perform and it would be prudent to test

**Comment by formatc1702** [comment]
I won't be able to take a closer look today, but that all sounds very good.

Just be careful with ‘build_examples.py` as that will cause conflicts with #118... I suggest reverting any changes there, and rather working on @kvid's branch, submitting a PR to him directly so a controlled merge of both PRs is possible.

**Comment by kvid** [comment]
I recommend rebasing this branch onto the current `dev` to get rid of all the Merge entries in your history. It is easier to do this early. Otherwise, if you wait until preparing for merge-in (@formatc1702 seems to prefer rebasing into his `dev`), you might encounter more work dealing with conflicts then.

> Some refactor of `build_examples.py` to utilize `main()`...

It seems several of your refactoring changes of `build_examples.py` was already done in #110, and I have several commits on top of that in #118. Please isolate the changes needed to interface `main()` and the extra file extension(s).

**Comment by kvid** [comment]
@aakatz3 wrote:
> Whether YAML, arguments, and/or a central/default config file control the output, I'm not sure, but all seem decent (and ideally all three would be most flexible, even if the config has to be an additional argument)

One way to handle this combination of specifications, is to let the config file (if present) be the first of potentially several --prepend'ed YAML files. Then, later spesifications and finally any CLI options can override.

**Comment by slightlynybbled** [comment]
I'll wait until #110 and #118 are merged.  My PR doesn't build as-is without changes to `build_examples.py`.

**Comment by formatc1702** [comment]
> I'll wait until #110 and #118 are merged. My PR doesn't build as-is without changes to `build_examples.py`.

I'll set the status to Draft then, so I won't merge accidentaly before #118 is merged.

**Comment by formatc1702** [comment]
#118 has been merged into `dev`, so feel free to adapt this PR.

Before merging, I'd appreciate if you could compress the commit history a bit by squashing and thus removing intermediate commits, to keep the history clean. Otherwise, I would have to resort to squashing all PR commits into one, which isn't the best idea for a larger refactoring such as this one. Thanks!

**Comment by slightlynybbled** [comment]
I messed with this for longer than I care to admit... I don't know how to squash.

**Comment by kvid** [comment]
> I messed with this for longer than I care to admit... I don't know how to squash. I think that some things are broken... could use an assist.

Do you normally use use command line `git` or some GUI client?

Personally, I normally use command line `git` together with `gitk` as a simple GUI client for visualizing branches and diffs between commits.

- First, I recommend using `gitk` or some other GUI client to get a grasp on what commits to combine, reorder, or eliminate.

- Then, I recommend running interactive rebase:  https://stackoverflow.com/questions/2302736/trimming-git-commits-squashing-git-history/2302947#2302947

- As an recent example, you can look at my commits to PR #118 before I rebased:  https://github.com/kvid/WireViz/commits/extended-build-examples-before-rebase

- I recommend creating a new branch at your starting point (as a bookmark), like I did: `git branch extended-build-examples-before-rebase`

- To deal with my last 15 commits, this command is used: `git rebase -i HEAD~15`

- Then, `git` showed me the commits in an editor:
```
pick 9ad3e13 Reduce code duplication by moving common code into a generic function
pick d4feae6 Add action to restore generated files from git repository
pick 64f6507 Add action to compare generated files against git repository
pick 099c202 Simplify code
pick ec29076 Make all actions honor the optional argument -generate
pick e3ad11a Move open_file_append() outside the if to avoid re-open
pick ba4b900 Avoid including readme in all file groups
pick 1ca8bd1 Simplify code
pick a9e7337 Rename some variables to better reflect their contents and relations
pick 58a54b2 Move test to include readme inside collect_filenames() function
pick f2a0db0 Improve status output by adding group name
pick be28803 Restructure the group dict initialization
pick d3b299b Rename -generate option to -g/--groups and add argument help
pick b4f9829 Move group loop into build_generated() for consistency
pick 253cb3a Add CLI option -c that allows comparing Graphviz output also

# Rebase 94b3ffa..253cb3a onto 94b3ffa (15 commands)
#
# Commands:
# p, pick = use commit
# r, reword = use commit, but edit the commit message
# e, edit = use commit, but stop for amending
# s, squash = use commit, but meld into previous commit
# f, fixup = like "squash", but discard this commit's log message
# x, exec = run command (the rest of the line) using shell
# d, drop = remove commit
#
# These lines can be re-ordered; they are executed from top to bottom.
#
# If you remove a line here THAT COMMIT WILL BE LOST.
#
# However, if you remove everything, the rebase will be aborted.
#
# Note that empty commits are commented out
```

- I decided to combine my first 4 commits into one, then combine my next 9 commits (except be28803) into another one, and then keep the rest as single commits. First, I moved the line with be28803 below the line with d3b299b (i.e. swapping the order of these two commits). Then I replaced the leading `pick` with `squash` (or simply `s`) on all lines containg commits I wanted to squash together with with the commit above, like this:
```
pick 9ad3e13 Reduce code duplication by moving common code into a generic function
squash d4feae6 Add action to restore generated files from git repository
squash 64f6507 Add action to compare generated files against git repository
squash 099c202 Simplify code
pick ec29076 Make all actions honor the optional argument -generate
squash e3ad11a Move open_file_append() outside the if to avoid re-open
squash ba4b900 Avoid including readme in all file groups
squash 1ca8bd1 Simplify code
squash a9e7337 Rename some variables to better reflect their contents and relations
squash 58a54b2 Move test to include readme inside collect_filenames() function
squash f2a0db0 Improve status output by adding group name
squash d3b299b Rename -generate option to -g/--groups and add argument help
pick be28803 Restructure the group dict initialization
pick b4f9829 Move group loop into build_generated() for consistency
pick 253cb3a Add CLI option -c that allows comparing Graphviz output also
```

- During the process, you are offered to edit the combined commit description of your squash commits, and handle any conflicts, e.g. when reordering commits.

- This is how my branch ended up:  https://github.com/kvid/WireViz/commits/extended-build-examples

- Take a look at my combined commits and compare them with the individual commits in the old branch.

- If you make a mistake or are not fully satisfied with the result, you can always go back to the old branch via the "bookmark" branch you created, and start all over.

- When satisfied, then I recommend rebasing your shorter branch onto the current `dev` branch (assuming you already have the official repo as a remote called e.g. `forked_from`) :
```
git checkout -b official-dev forked_from/dev
git checkout dev
git branch my-dev-before-rebase-to-official-dev
git rebase official-dev
```

- During this process, you normally need to handle conflicts.

- As before, if you make a mistake or are not fully satisfied with the result, you can always go back to the old branch via the `my-dev-before-rebase-to-official-dev` branch you created, and start from there again.

**Comment by formatc1702** [comment]
That is some fantastic advice right there. Thank you @kvid.

**Comment by formatc1702** [comment]
Any progress on the commit restructuring? I'm afraid it's not possible for me or @kvid to check out the PR and do the squashing, without removing @slightlynybbled's authorship, which would be a shame. But maybe there is some way to help out that I'm not aware of?

**Comment by formatc1702** [comment]
Since there has not been any progress on this front, I will move this topic to the v0.3 milestone, since I want to get v0.2 released soon. This shouldn't be a huge deal-breaker, and it's no problem to release v0.3 soon if something happens here shortly after release.

**Comment by formatc1702** [comment]
@slightlynybbled , I hope you're well and I'm wondering whether you are able to keep working on getting this PR ready for a merge?

**Comment by slightlynybbled** [comment]
I'm going to close the pull request and do a fresh try later.  Too much has happened and I don't think that the PR in its current form is easily salvageable.

**Pull request closed without merging**
